export const PRIORITIES = ['High', 'Medium', 'Low'];
export const FILTERS = ['All', 'Today', 'Upcoming', 'Done'];

export const createTodo = ({
  title,
  note = '',
  due = 'Today',
  priority = 'Medium',
  tags = [],
  reminderMinutes = 0,
}) => ({
  id: String(Date.now()),
  title,
  note,
  due,
  priority,
  tags,
  completed: false,
  starred: false,
  reminderMinutes,
  reminderId: null,
  reminderSetAt: reminderMinutes > 0 ? Date.now() : null,
  order: Date.now(),
});

export const seedTodos = [
  {
    id: '1',
    title: 'Map the onboarding flow',
    note: 'Sketch 3 paths and pick the cleanest',
    due: 'Today',
    priority: 'High',
    tags: ['Design', 'Product'],
    completed: false,
    starred: true,
    reminderMinutes: 0,
    reminderId: null,
    reminderSetAt: null,
    order: 1,
  },
  {
    id: '2',
    title: 'Team sync',
    note: 'Share sprint goals and risks',
    due: 'Today',
    priority: 'Medium',
    tags: ['Work'],
    completed: false,
    starred: false,
    reminderMinutes: 0,
    reminderId: null,
    reminderSetAt: null,
    order: 2,
  },
  {
    id: '3',
    title: 'Grocery run',
    note: 'Veggies, fruit, coffee beans',
    due: 'Tomorrow',
    priority: 'Low',
    tags: ['Personal'],
    completed: false,
    starred: false,
    reminderMinutes: 0,
    reminderId: null,
    reminderSetAt: null,
    order: 3,
  },
  {
    id: '4',
    title: 'Stretch + mobility',
    note: '15 min shoulders and hips',
    due: 'Upcoming',
    priority: 'Low',
    tags: ['Wellness'],
    completed: true,
    starred: false,
    reminderMinutes: 0,
    reminderId: null,
    reminderSetAt: null,
    order: 4,
  },
];
